### ISSUE TITLE
[Improve Documentation] : Python 3 is not compatible

### ISSUE THREAD

**Issue by mohdsanadzakirizvi** [rdangovs/rotational-unit-of-memory#4]
I suggest mentioning the project dependencies in the **README.md** as a lot of people will face this issue.

**Comment by whenafirestartstoburn** [comment]
Yes! And because of that launch on windows is impossible, because Tensorflow has no build for python 2 on windows.

If it is ok, could you please give information about what operating system your solution is developed for?

**Comment by rdangovs** [comment]
Thank you: the documentation is updated and the code is now compatible with Python 3.
